baseURL = 'https://resume.rob-wolfe.com'
languageCode = 'en-us'
title = 'Rob Wolfe Resume - Long Version'
theme = 'almeida-cv'
publishDir = "c:/websites/resume.portwallistechnologies.com"
[params]
pages = 5

